### PR TITLE
allow horde-installer-plugin in release pipeline

### PR DESCRIPTION
**Pull request by boekhorstb1**

### CODE REVIEW

**Comment by ralflang** [comment]
Something makes the unit tests for pecl/http fail, possibly unrelated

**Comment by boekhorstb1** [comment]
ok will take a loot at it

**Comment by boekhorstb1** [comment]
the pecl/http test are not failing, they are skipped because for example the class HttpRequest is missing. That class is only available in v1 of the PECL extension I think (the new version is at v3 I think). So if certain versions of the extension are not there, the tests are being skipped.... I don't think all those dependencies need to be installed so the tests run, right?

**Comment by boekhorstb1** [comment]
the two failed test that do occure are related to checkHeaderForInvalidAsciiChars() in src/MessageImplementation.php.. which I wrote :) I will look into it

**Comment by boekhorstb1** [comment]
see https://github.com/maintaina-com/Http/pull/15

**Pull request merged**
